<?php
$ID_BERESHITH                   = 0;
$ID_NOAH                        = 1;
$ID_LEHLEHA                     = 2;
$ID_VAYERA                      = 3;
$ID_HAYESARAH                   = 4;
$ID_TOLEDOTH                    = 5;
$ID_VAYETSE                     = 6;
$ID_VAYISHLAH                   = 7;
$ID_VAYESHEB                    = 8;
$ID_MIKKETS                     = 9;
$ID_VAYIGGASH                  = 10;
$ID_VAYHEE                     = 11;
$ID_SHEMOTH                    = 12;
$ID_VAERA                      = 13;
$ID_BO                         = 14;
$ID_BESHALLAH                  = 15;
$ID_YITHRO                     = 16;
$ID_MISHPATIM                  = 17;
$ID_TERUMAH                    = 18;
$ID_TETSAVVEH                  = 19;
$ID_KITISSA                    = 20;
$ID_VAYAKHEL                   = 21;
$ID_PEKUDE                     = 22;
$ID_VAYIKRA                    = 23;
$ID_TSAV                       = 24;
$ID_SHEMINI                    = 25;
$ID_TAZRIANG                   = 26;
$ID_METSORANG                  = 27;
$ID_AHAREMOTH                  = 28;
$ID_KEDOSHIM                   = 29;
$ID_EMOR                       = 30;
$ID_BEHAR                      = 31;
$ID_BEHUKKOTHAI                = 32;
$ID_BEMIDBAR                   = 33;
$ID_NASO                       = 34;
$ID_BEHAALOTEHA                = 35;
$ID_SHELAHLEHA                 = 36;
$ID_KORAH                      = 37;
$ID_HUKATH                     = 38;
$ID_BALAK                      = 39;
$ID_PINHAS                     = 40;
$ID_MATOTH                     = 41;
$ID_MASEH                      = 42;
$ID_DEBARIM                    = 43;
$ID_VAETHANAN                  = 44;
$ID_EKEB                       = 45;
$ID_REEH                       = 46;
$ID_SHOFETIM                   = 47;
$ID_KITETSE                    = 48;
$ID_KITABO                     = 49;
$ID_NITSABIM                   = 50;
$ID_VAYELEH                    = 51;
$ID_HAAZINU                    = 52;

$ID_SIMHATHTORAH               = 53;
$ID_SIMHATHTORAH_2             = 54;
$ID_SIMHATHTORAH_3             = 55;

$ID_ROSH_HODESH_SHABBAT        = 60;
$ID_SHEKALIM                   = 61;
$ID_ZAHOR                      = 62;
$ID_PARAH                      = 63;
$ID_HAHODESH                   = 64;
$ID_HAGGADOL                   = 65;
$ID_SHUVA                      = 66;

$ID_ROSH_HASHANAH_I            = 70;
$ID_ROSH_HASHANAH_II           = 71;
$ID_FAST_OF_GEDALIAH           = 72;
$ID_YOM_KIPPUR                 = 73;
$ID_SUCCOTH_I                  = 74;
$ID_SUCCOTH_II                 = 75;
$ID_SUCCOTH_III_NO_SHABBAT     = 76;
$ID_SUCCOTH_III                = 77;
$ID_SUCCOTH_IV                 = 78;
$ID_SUCCOTH_V_NO_SHABBAT       = 79;
$ID_SUCCOTH_V                  = 80;
$ID_SUCCOTH_VI_NO_SHABBAT      = 81;
$ID_SUCCOTH_VI                 = 82;
$ID_HOSHANAH_RABBAH            = 83;
$ID_HOL_HAMOED_SUCCOTH         = 84;
$ID_SHEMINI_AZERETH_1          = 85;
$ID_FAST_OF_ESTHER             = 86;
$ID_PURIM                      = 87;
$ID_FAST_OF_TEVET_10           = 88;
$ID_PESAH_I                    = 89;
$ID_HOL_HAMOED_PESAH           = 90;
$ID_PESAH_VII                  = 91;
$ID_PESAH_VIII                 = 92;
$ID_PESAH_VIII_NO_SHABBAT      = 93;
$ID_SHAVUOTH_I                 = 94;
$ID_SHAVUOTH_II_NO_SHABBAT     = 95; 
$ID_SHAVUOTH_II                = 96;
$ID_YOM_HAATZMAUT              = 97;
$ID_FAST_OF_TAMMUZ_17          = 98;
$ID_FAST_OF_TISHA_BAV          = 99;
$ID_CHANUKKAH_I               = 100;
$ID_CHANUKKAH_II              = 101;
$ID_CHANUKKAH_III             = 102;
$ID_CHANUKKAH_IV              = 103;
$ID_CHANUKKAH_V               = 104;
$ID_CHANUKKAH_VI              = 105;
$ID_CHANUKKAH_VI_ROSH_HODESH  = 106;
$ID_CHANUKKAH_VII             = 107;
$ID_CHANUKKAH_VII_ROSH_HODESH = 108;
$ID_CHANUKKAH_VIII            = 109;
$ID_SECOND_SHABBAT_CHANUKKAH  = 110;
$ID_ROSH_HODESH               = 111;
$ID_PESAH_II                  = 112;
$ID_PESAH_III                 = 113;
$ID_PESAH_IV                  = 114;
$ID_PESAH_IV_NOT_SUNDAY       = 115;
$ID_PESAH_IV_SUNDAY           = 116;
$ID_PESAH_V                   = 117;
$ID_PESAH_V_NOT_MONDAY        = 118;
$ID_PESAH_V_MONDAY            = 119;
$ID_PESAH_VI                  = 120;

$ID_SPECIAL_1                  = 150;
$ID_SPECIAL_2                  = 151;
$ID_SPECIAL_3                  = 152;
$ID_SPECIAL_4                  = 153;
$ID_SPECIAL_5                  = 154;
$ID_SPECIAL_6                  = 155;
$ID_SPECIAL_7                  = 156;
$ID_SPECIAL_8                  = 157;
$ID_SPECIAL_8A                 = 158;
$ID_SPECIAL_9                  = 159;
$ID_SPECIAL_10                 = 161;
$ID_SPECIAL_11                 = 162;
$ID_SPECIAL_12                 = 163;

$ID_SHEMINI_AZERETH_2          = 170;
$ID_SHEMINI_AZERETH_3          = 171;
$ID_SHEMINI_AZERETH            = 172;

$ID_MAX                        = 256;

$ID_NULL                       = 1000;

$torahSectionsA = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_PARAH,   $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_HAHODESH,  /* 22 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 25 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 29 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 40 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 48 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_YOM_KIPPUR,          $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 51 */

$torahSectionsB = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_ZAHOR,   $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_PARAH,   $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_HAHODESH,  /* 22 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 24 */
   $ID_PESAH_VII,           $ID_NULL,    $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 27 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 28 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 30 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 39 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 50 */

$torahSectionsCDiaspora = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_PARAH,   $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_HAHODESH,  /* 22 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 25 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 29 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_SHAVUOTH_II,         $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_HUKATH,              $ID_BALAK,   $ID_NULL,      /* 38 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 40 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 48 */
   $ID_ROSH_HASHANAH_I,     $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_SUCCOTH_I,           $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_SHEMINI_AZERETH,     $ID_NULL,    $ID_NULL);     /* 52 */

$torahSectionsCIsrael = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_PARAH,   $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_HAHODESH,  /* 22 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 25 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 29 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 40 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 48 */
   $ID_ROSH_HASHANAH_I,     $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_SUCCOTH_I,           $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_SHEMINI_AZERETH,     $ID_NULL,    $ID_NULL);     /* 52 */

$torahSectionsDDiaspora = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_PARAH,     /* 22 */
   $ID_VAYIKRA,             $ID_HAHODESH,$ID_NULL,      /* 23 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 24 */
   $ID_PESAH_I,             $ID_NULL,    $ID_NULL,      /* 25 */
   $ID_PESAH_VIII,          $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 29 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 40 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 51 */

$torahSectionsDIsrael = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_PARAH,     /* 22 */
   $ID_VAYIKRA,             $ID_HAHODESH,$ID_NULL,      /* 23 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 24 */
   $ID_PESAH_I,             $ID_NULL,    $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 27 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 28 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 40 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 51 */

$torahSectionsEDiaspora = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_PARAH,   $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_HAHODESH,  /* 22 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 24 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 29 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_SHAVUOTH_II,         $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_HUKATH,              $ID_BALAK,   $ID_NULL,      /* 38 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 40 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 48 */
   $ID_ROSH_HASHANAH_I,     $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_SUCCOTH_I,           $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_SHEMINI_AZERETH,     $ID_NULL,    $ID_NULL);     /* 52 */

$torahSectionsEIsrael = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_PARAH,   $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_HAHODESH,  /* 22 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 24 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 29 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_SHAVUOTH_II,         $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_HUKATH,              $ID_BALAK,   $ID_NULL,      /* 38 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 40 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 48 */
   $ID_ROSH_HASHANAH_I,     $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_SUCCOTH_I,           $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_SHEMINI_AZERETH,     $ID_NULL,    $ID_NULL);     /* 52 */

$torahSectionsF = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_SHEKALIM,$ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PARAH,   $ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_HAHODESH,$ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 25 */
   $ID_PESAH_VII,           $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 29 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 41 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 52 */

$torahSectionsG = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_SHEKALIM,$ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_ZAHOR,   $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_PARAH,   $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_PEKUDE,  $ID_HAHODESH,  /* 22 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_HAGGADOL,$ID_NULL,      /* 25 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 26 */
   $ID_SHEMINI,             $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_TAZRIANG,           $ID_METSORANG,$ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_KEDOSHIM,$ID_NULL,      /* 29 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_BEHAR,            $ID_BEHUKKOTHAI,$ID_NULL,      /* 31 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 40 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 48 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_YOM_KIPPUR,          $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 51 */

$torahSectionsHDiaspora = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,   $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_PARAH,   $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_HAHODESH,$ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_SHAVUOTH_II,         $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_HUKATH,              $ID_BALAK,   $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 43 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 51 */
   $ID_ROSH_HASHANAH_I,     $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_SUCCOTH_I,           $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_SHEMINI_AZERETH,     $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsHIsrael = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,   $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_PARAH,   $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_HAHODESH,$ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 43 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 51 */
   $ID_ROSH_HASHANAH_I,     $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_SUCCOTH_I,           $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_SHEMINI_AZERETH,     $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsI = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_NULL,    $ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_SHEKALIM,$ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,   $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_NULL,    $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_PARAH,   $ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_HAHODESH,$ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_NULL,    $ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_HAGGADOL,$ID_NULL,      /* 29 */
   $ID_PESAH_VII,           $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_MASEH,               $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsJ = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,   $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_PARAH,   $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_HAHODESH,$ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 43 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 51 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_YOM_KIPPUR,          $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 54 */

$torahSectionsKDiaspora = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,   $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_NULL,    $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_PARAH,   $ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_HAHODESH,$ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_PESAH_I,             $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_PESAH_VIII,          $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 44 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsKIsrael = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,   $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_NULL,    $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_PARAH,   $ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_HAHODESH,$ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_PESAH_I,             $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_MASEH,               $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsLDiaspora = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,  $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_NULL,    $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_PARAH,   $ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_HAHODESH,$ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_PESAH_I,             $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_PESAH_VIII,          $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 44 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsLIsrael = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,  $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_NULL,    $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_PARAH,   $ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_HAHODESH,$ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_PESAH_I,             $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_MASEH,               $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_NITSABIM,            $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_VAYELEH,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsM = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_NULL,    $ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_SHEKALIM,$ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_NULL,    $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_ZAHOR,   $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_PARAH,   $ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_HAHODESH,$ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_NULL,    $ID_NULL,      /* 28 */
   $ID_AHAREMOTH,           $ID_HAGGADOL,$ID_NULL,      /* 29 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_NULL,    $ID_NULL,      /* 43 */
   $ID_MASEH,               $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 51 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 52 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_YOM_KIPPUR,          $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_HOL_HAMOED_SUCCOTH,  $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsNDiaspora = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,   $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_PARAH,   $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_HAHODESH,$ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_SHAVUOTH_II,         $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_HUKATH,              $ID_BALAK,   $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 43 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 51 */
   $ID_ROSH_HASHANAH_I,     $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_SUCCOTH_I,           $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_SHEMINI_AZERETH,     $ID_NULL,    $ID_NULL);     /* 55 */

$torahSectionsNIsrael = array
  ($ID_BERESHITH,           $ID_NULL,    $ID_NULL,      /*  1 */
   $ID_NOAH,                $ID_NULL,    $ID_NULL,      /*  2 */
   $ID_LEHLEHA,             $ID_NULL,    $ID_NULL,      /*  3 */
   $ID_VAYERA,              $ID_NULL,    $ID_NULL,      /*  4 */
   $ID_HAYESARAH,           $ID_NULL,    $ID_NULL,      /*  5 */
   $ID_TOLEDOTH,            $ID_NULL,    $ID_NULL,      /*  6 */
   $ID_VAYETSE,             $ID_NULL,    $ID_NULL,      /*  7 */
   $ID_VAYISHLAH,           $ID_NULL,    $ID_NULL,      /*  8 */
   $ID_VAYESHEB,            $ID_NULL,    $ID_NULL,      /*  9 */
   $ID_MIKKETS,             $ID_NULL,    $ID_NULL,      /* 10 */
   $ID_VAYIGGASH,           $ID_NULL,    $ID_NULL,      /* 11 */
   $ID_VAYHEE,              $ID_NULL,    $ID_NULL,      /* 12 */
   $ID_SHEMOTH,             $ID_NULL,    $ID_NULL,      /* 13 */
   $ID_VAERA,               $ID_NULL,    $ID_NULL,      /* 14 */
   $ID_BO,                  $ID_NULL,    $ID_NULL,      /* 15 */
   $ID_BESHALLAH,           $ID_NULL,    $ID_NULL,      /* 16 */
   $ID_YITHRO,              $ID_NULL,    $ID_NULL,      /* 17 */
   $ID_MISHPATIM,           $ID_NULL,    $ID_NULL,      /* 18 */
   $ID_TERUMAH,             $ID_NULL,    $ID_NULL,      /* 19 */
   $ID_TETSAVVEH,           $ID_NULL,    $ID_NULL,      /* 20 */
   $ID_KITISSA,             $ID_NULL,    $ID_NULL,      /* 21 */
   $ID_VAYAKHEL,            $ID_SHEKALIM,$ID_NULL,      /* 22 */
   $ID_PEKUDE,              $ID_NULL,    $ID_NULL,      /* 23 */
   $ID_VAYIKRA,             $ID_ZAHOR,   $ID_NULL,      /* 24 */
   $ID_TSAV,                $ID_PARAH,   $ID_NULL,      /* 25 */
   $ID_SHEMINI,             $ID_HAHODESH,$ID_NULL,      /* 26 */
   $ID_TAZRIANG,            $ID_NULL,    $ID_NULL,      /* 27 */
   $ID_METSORANG,           $ID_HAGGADOL,$ID_NULL,      /* 28 */
   $ID_HOL_HAMOED_PESAH,    $ID_NULL,    $ID_NULL,      /* 29 */
   $ID_AHAREMOTH,           $ID_NULL,    $ID_NULL,      /* 30 */
   $ID_KEDOSHIM,            $ID_NULL,    $ID_NULL,      /* 31 */
   $ID_EMOR,                $ID_NULL,    $ID_NULL,      /* 32 */
   $ID_BEHAR,               $ID_NULL,    $ID_NULL,      /* 33 */
   $ID_BEHUKKOTHAI,         $ID_NULL,    $ID_NULL,      /* 34 */
   $ID_BEMIDBAR,            $ID_NULL,    $ID_NULL,      /* 35 */
   $ID_NASO,                $ID_NULL,    $ID_NULL,      /* 36 */
   $ID_BEHAALOTEHA,         $ID_NULL,    $ID_NULL,      /* 37 */
   $ID_SHELAHLEHA,          $ID_NULL,    $ID_NULL,      /* 38 */
   $ID_KORAH,               $ID_NULL,    $ID_NULL,      /* 39 */
   $ID_HUKATH,              $ID_NULL,    $ID_NULL,      /* 40 */
   $ID_BALAK,               $ID_NULL,    $ID_NULL,      /* 41 */
   $ID_PINHAS,              $ID_NULL,    $ID_NULL,      /* 42 */
   $ID_MATOTH,              $ID_MASEH,   $ID_NULL,      /* 43 */
   $ID_DEBARIM,             $ID_NULL,    $ID_NULL,      /* 44 */
   $ID_VAETHANAN,           $ID_NULL,    $ID_NULL,      /* 45 */
   $ID_EKEB,                $ID_NULL,    $ID_NULL,      /* 46 */
   $ID_REEH,                $ID_NULL,    $ID_NULL,      /* 47 */
   $ID_SHOFETIM,            $ID_NULL,    $ID_NULL,      /* 48 */
   $ID_KITETSE,             $ID_NULL,    $ID_NULL,      /* 49 */
   $ID_KITABO,              $ID_NULL,    $ID_NULL,      /* 50 */
   $ID_NITSABIM,            $ID_VAYELEH, $ID_NULL,      /* 51 */
   $ID_ROSH_HASHANAH_I,     $ID_NULL,    $ID_NULL,      /* 52 */
   $ID_HAAZINU,             $ID_NULL,    $ID_NULL,      /* 53 */
   $ID_SUCCOTH_I,           $ID_NULL,    $ID_NULL,      /* 54 */
   $ID_SHEMINI_AZERETH,     $ID_NULL,    $ID_NULL);     /* 55 */

function torahGetWeekday($absDate) {
  return jddayofweek($absDate, 0);
}

function torahHebrewLeapYear($year) {
  if (((($year*7)+1) % 19) < 7)
    return true;
  else
    return false;
}

function torahLastMonthOfHebrewYear($year) {
  if (torahHebrewLeapYear($year))
    return 13;
  else
    return 12;
}

function getYearType($year) {
  $rhWeekday = torahGetWeekday(jewishtojd(1, 1, $year));
  $lengthOfYear = jewishtojd(1, 1, $year+1) - jewishtojd(1, 1, $year);
  $pesWeekday = torahGetWeekday(jewishtojd(8, 15, $year));

  if (($rhWeekday == 1) && ($lengthOfYear == 353) && ($pesWeekday == 2)) return 1;
  if (($rhWeekday == 6) && ($lengthOfYear == 353) && ($pesWeekday == 0)) return 2;
  if (($rhWeekday == 2) && ($lengthOfYear == 354) && ($pesWeekday == 4)) return 3;
  if (($rhWeekday == 4) && ($lengthOfYear == 354) && ($pesWeekday == 6)) return 4;
  if (($rhWeekday == 1) && ($lengthOfYear == 355) && ($pesWeekday == 4)) return 5;
  if (($rhWeekday == 4) && ($lengthOfYear == 355) && ($pesWeekday == 0)) return 6;
  if (($rhWeekday == 6) && ($lengthOfYear == 355) && ($pesWeekday == 2)) return 7;

  if (($rhWeekday == 1) && ($lengthOfYear == 383) && ($pesWeekday == 4)) return 8;
  if (($rhWeekday == 4) && ($lengthOfYear == 383) && ($pesWeekday == 0)) return 9;
  if (($rhWeekday == 6) && ($lengthOfYear == 383) && ($pesWeekday == 2)) return 10;
  if (($rhWeekday == 2) && ($lengthOfYear == 384) && ($pesWeekday == 6)) return 11;
  if (($rhWeekday == 1) && ($lengthOfYear == 385) && ($pesWeekday == 6)) return 12;
  if (($rhWeekday == 4) && ($lengthOfYear == 385) && ($pesWeekday == 2)) return 13;
  if (($rhWeekday == 6) && ($lengthOfYear == 385) && ($pesWeekday == 4)) return 14;

  return 0;
}

function determineBereshith($year) {
  $simchatTorah = jewishtojd(1, 23, $year);
  while (torahGetWeekday($simchatTorah) != 6) {
    $simchatTorah++;
  }
  return ($simchatTorah);
}

function getTorahSectionName($section) {
  global $ID_BERESHITH, $ID_NOAH, $ID_LEHLEHA, $ID_VAYERA, $ID_HAYESARAH;
  global $ID_TOLEDOTH, $ID_VAYETSE, $ID_VAYISHLAH, $ID_VAYESHEB, $ID_MIKKETS;
  global $ID_VAYIGGASH, $ID_VAYHEE, $ID_SHEMOTH, $ID_VAERA, $ID_BO;
  global $ID_BESHALLAH, $ID_YITHRO, $ID_MISHPATIM, $ID_TERUMAH, $ID_TETSAVVEH;
  global $ID_KITISSA, $ID_VAYAKHEL, $ID_PEKUDE, $ID_VAYIKRA, $ID_TSAV;
  global $ID_SHEMINI, $ID_TAZRIANG, $ID_METSORANG, $ID_AHAREMOTH;
  global $ID_KEDOSHIM, $ID_EMOR, $ID_BEHAR, $ID_BEHUKKOTHAI, $ID_BEMIDBAR;
  global $ID_NASO, $ID_BEHAALOTEHA, $ID_SHELAHLEHA, $ID_KORAH, $ID_HUKATH;
  global $ID_BALAK, $ID_PINHAS, $ID_MATOTH, $ID_MASEH, $ID_DEBARIM;
  global $ID_VAETHANAN, $ID_EKEB, $ID_REEH, $ID_SHOFETIM, $ID_KITETSE;
  global $ID_KITABO, $ID_NITSABIM, $ID_VAYELEH, $ID_HAAZINU;
  global $ID_SHEKALIM, $ID_ZAHOR, $ID_PARAH, $ID_HAHODESH, $ID_SHUVA;

  if ($section == $ID_BERESHITH) return "Berešit";
  if ($section == $ID_NOAH) return "Noach";
  if ($section == $ID_LEHLEHA) return "Lech Lecha";
  if ($section == $ID_VAYERA) return "Vajera";
  if ($section == $ID_HAYESARAH) return "Chaje Sara";
  if ($section == $ID_TOLEDOTH) return "Tol'dot";
  if ($section == $ID_VAYETSE) return "Vajece";
  if ($section == $ID_VAYISHLAH) return "Vajišlach";
  if ($section == $ID_VAYESHEB) return "Vaješev";
  if ($section == $ID_MIKKETS) return "Mikec";
  if ($section == $ID_VAYIGGASH) return "Vajigaš";
  if ($section == $ID_VAYHEE) return "Vajchi";
  if ($section == $ID_SHEMOTH) return "Šemot";
  if ($section == $ID_VAERA) return "Vaera";
  if ($section == $ID_BO) return "Bo";
  if ($section == $ID_BESHALLAH) return "Bešalach, Šabat Shira";
  if ($section == $ID_YITHRO) return "Jitro";
  if ($section == $ID_MISHPATIM) return "Mišpatim";
  if ($section == $ID_TERUMAH) return "Teruma";
  if ($section == $ID_TETSAVVEH) return "Tecave";
  if ($section == $ID_KITISSA) return "Ki Tisa";
  if ($section == $ID_VAYAKHEL) return "Vajakhel";
  if ($section == $ID_PEKUDE) return "Pekudej";
  if ($section == $ID_VAYIKRA) return "Vajikra";
  if ($section == $ID_TSAV) return "Cav";
  if ($section == $ID_SHEMINI) return "Šemini";
  if ($section == $ID_TAZRIANG) return "Tazria";
  if ($section == $ID_METSORANG) return "Mecora";
  if ($section == $ID_AHAREMOTH) return "Acharej mot";
  if ($section == $ID_KEDOSHIM) return "Kedošim";
  if ($section == $ID_EMOR) return "Emor";
  if ($section == $ID_BEHAR) return "Behar";
  if ($section == $ID_BEHUKKOTHAI) return "Bechukotaj";
  if ($section == $ID_BEMIDBAR) return "Bemidbar";
  if ($section == $ID_NASO) return "Naso";
  if ($section == $ID_BEHAALOTEHA) return "Beha'alotcha";
  if ($section == $ID_SHELAHLEHA) return "Šelach lecha";
  if ($section == $ID_KORAH) return "Korach";
  if ($section == $ID_HUKATH) return "Chukat";
  if ($section == $ID_BALAK) return "Balak";
  if ($section == $ID_PINHAS) return "Pinchas";
  if ($section == $ID_MATOTH) return "Matot";
  if ($section == $ID_MASEH) return "Mase";
  if ($section == $ID_DEBARIM) return "Devarim, Šabat Chazon";
  if ($section == $ID_VAETHANAN) return "Vaetchanan, Šabat Nechamu";
  if ($section == $ID_EKEB) return "Ekev";
  if ($section == $ID_REEH) return "Re'e";
  if ($section == $ID_SHOFETIM) return "Šoftim";
  if ($section == $ID_KITETSE) return "Ki Tece";
  if ($section == $ID_KITABO) return "Ki Tavo";
  if ($section == $ID_NITSABIM) return "Nicavim";
  if ($section == $ID_VAYELEH) return "Vajelech";
  if ($section == $ID_HAAZINU) return "Ha'azinu";

  if ($section == $ID_SHEKALIM) return "Šabat Šekalim";
  if ($section == $ID_ZAHOR) return "Šabat Zachor";
  if ($section == $ID_PARAH) return "Šabat Para";
  if ($section == $ID_HAHODESH) return "Šabat Hachodeš";
  if ($section == $ID_SHUVA) return "Šabat Šuva";

  return "";
}

function getTorahSectionLinkHelper($book, $chapter, $verse) {
  if ($book < 10)
    $bookStr = "0" . $book;
  else
    $bookStr = $book;
  if ($chapter < 10)
    $chapterStr = "0" . $chapter;
  else
    $chapterStr = $chapter;
  return "http://www.mechon-mamre.org/i/t/t$bookStr$chapterStr.htm#$verse";
}

function getTorahSectionLink($section) {
  global $ID_BERESHITH, $ID_NOAH, $ID_LEHLEHA, $ID_VAYERA, $ID_HAYESARAH;
  global $ID_TOLEDOTH, $ID_VAYETSE, $ID_VAYISHLAH, $ID_VAYESHEB, $ID_MIKKETS;
  global $ID_VAYIGGASH, $ID_VAYHEE, $ID_SHEMOTH, $ID_VAERA, $ID_BO;
  global $ID_BESHALLAH, $ID_YITHRO, $ID_MISHPATIM, $ID_TERUMAH, $ID_TETSAVVEH;
  global $ID_KITISSA, $ID_VAYAKHEL, $ID_PEKUDE, $ID_VAYIKRA, $ID_TSAV;
  global $ID_SHEMINI, $ID_TAZRIANG, $ID_METSORANG, $ID_AHAREMOTH;
  global $ID_KEDOSHIM, $ID_EMOR, $ID_BEHAR, $ID_BEHUKKOTHAI, $ID_BEMIDBAR;
  global $ID_NASO, $ID_BEHAALOTEHA, $ID_SHELAHLEHA, $ID_KORAH, $ID_HUKATH;
  global $ID_BALAK, $ID_PINHAS, $ID_MATOTH, $ID_MASEH, $ID_DEBARIM;
  global $ID_VAETHANAN, $ID_EKEB, $ID_REEH, $ID_SHOFETIM, $ID_KITETSE;
  global $ID_KITABO, $ID_NITSABIM, $ID_VAYELEH, $ID_HAAZINU;
  global $ID_SHEKALIM, $ID_ZAHOR, $ID_PARAH, $ID_HAHODESH;

  $GENESIS = 1;
  $EXODUS = 2;
  $LEVITICUS = 3;
  $NUMERI = 4;
  $DEUTERONOMY = 5;

  if ($section == $ID_BERESHITH) return getTorahSectionLinkHelper($GENESIS, 1, 1);
  if ($section == $ID_NOAH) return getTorahSectionLinkHelper($GENESIS, 6, 9);
  if ($section == $ID_LEHLEHA) return getTorahSectionLinkHelper($GENESIS, 12, 1);
  if ($section == $ID_VAYERA) return getTorahSectionLinkHelper($GENESIS, 18, 1);
  if ($section == $ID_HAYESARAH) return getTorahSectionLinkHelper($GENESIS, 23, 1);
  if ($section == $ID_TOLEDOTH) return getTorahSectionLinkHelper($GENESIS, 25, 19);
  if ($section == $ID_VAYETSE) return getTorahSectionLinkHelper($GENESIS, 28, 10);
  if ($section == $ID_VAYISHLAH) return getTorahSectionLinkHelper($GENESIS, 32, 4);
  if ($section == $ID_VAYESHEB) return getTorahSectionLinkHelper($GENESIS, 37, 1);
  if ($section == $ID_MIKKETS) return getTorahSectionLinkHelper($GENESIS, 41, 1);
  if ($section == $ID_VAYIGGASH) return getTorahSectionLinkHelper($GENESIS, 44, 18);
  if ($section == $ID_VAYHEE) return getTorahSectionLinkHelper($GENESIS, 47, 28);
  if ($section == $ID_SHEMOTH) return getTorahSectionLinkHelper($EXODUS, 1, 1);
  if ($section == $ID_VAERA) return getTorahSectionLinkHelper($EXODUS, 6, 2);
  if ($section == $ID_BO) return getTorahSectionLinkHelper($EXODUS, 10, 1);
  if ($section == $ID_BESHALLAH) return getTorahSectionLinkHelper($EXODUS, 13, 17);
  if ($section == $ID_YITHRO) return getTorahSectionLinkHelper($EXODUS, 18, 1);
  if ($section == $ID_MISHPATIM) return getTorahSectionLinkHelper($EXODUS, 21, 1);
  if ($section == $ID_TERUMAH) return getTorahSectionLinkHelper($EXODUS, 25, 1);
  if ($section == $ID_TETSAVVEH) return getTorahSectionLinkHelper($EXODUS, 27, 20);
  if ($section == $ID_KITISSA) return getTorahSectionLinkHelper($EXODUS, 30, 11);
  if ($section == $ID_VAYAKHEL) return getTorahSectionLinkHelper($EXODUS, 35, 1);
  if ($section == $ID_PEKUDE) return getTorahSectionLinkHelper($EXODUS, 38, 21);
  if ($section == $ID_VAYIKRA) return getTorahSectionLinkHelper($LEVITICUS, 1, 1);
  if ($section == $ID_TSAV) return getTorahSectionLinkHelper($LEVITICUS, 6, 1);
  if ($section == $ID_SHEMINI) return getTorahSectionLinkHelper($LEVITICUS, 9, 1);
  if ($section == $ID_TAZRIANG) return getTorahSectionLinkHelper($LEVITICUS, 12, 1);
  if ($section == $ID_METSORANG) return getTorahSectionLinkHelper($LEVITICUS, 14, 1);
  if ($section == $ID_AHAREMOTH) return getTorahSectionLinkHelper($LEVITICUS, 16, 1);
  if ($section == $ID_KEDOSHIM) return getTorahSectionLinkHelper($LEVITICUS, 19, 1);
  if ($section == $ID_EMOR) return getTorahSectionLinkHelper($LEVITICUS, 21, 1);
  if ($section == $ID_BEHAR) return getTorahSectionLinkHelper($LEVITICUS, 25, 1);
  if ($section == $ID_BEHUKKOTHAI) return getTorahSectionLinkHelper($LEVITICUS, 26, 3);
  if ($section == $ID_BEMIDBAR) return getTorahSectionLinkHelper($NUMERI, 1, 1);
  if ($section == $ID_NASO) return getTorahSectionLinkHelper($NUMERI, 4, 21);
  if ($section == $ID_BEHAALOTEHA) return getTorahSectionLinkHelper($NUMERI, 8, 1);
  if ($section == $ID_SHELAHLEHA) return getTorahSectionLinkHelper($NUMERI, 13, 1);
  if ($section == $ID_KORAH) return getTorahSectionLinkHelper($NUMERI, 16, 1);
  if ($section == $ID_HUKATH) return getTorahSectionLinkHelper($NUMERI, 19, 1);
  if ($section == $ID_BALAK) return getTorahSectionLinkHelper($NUMERI, 22, 2);
  if ($section == $ID_PINHAS) return getTorahSectionLinkHelper($NUMERI, 25, 10);
  if ($section == $ID_MATOTH) return getTorahSectionLinkHelper($NUMERI, 30, 2);
  if ($section == $ID_MASEH) return getTorahSectionLinkHelper($NUMERI, 33, 1);
  if ($section == $ID_DEBARIM) return getTorahSectionLinkHelper($DEUTERONOMY, 1, 1);
  if ($section == $ID_VAETHANAN) return getTorahSectionLinkHelper($DEUTERONOMY, 3, 23);
  if ($section == $ID_EKEB) return getTorahSectionLinkHelper($DEUTERONOMY, 7, 12);
  if ($section == $ID_REEH) return getTorahSectionLinkHelper($DEUTERONOMY, 11, 26);
  if ($section == $ID_SHOFETIM) return getTorahSectionLinkHelper($DEUTERONOMY, 16, 18);
  if ($section == $ID_KITETSE) return getTorahSectionLinkHelper($DEUTERONOMY, 21, 10);
  if ($section == $ID_KITABO) return getTorahSectionLinkHelper($DEUTERONOMY, 26, 1);
  if ($section == $ID_NITSABIM) return getTorahSectionLinkHelper($DEUTERONOMY, 29, 9);
  if ($section == $ID_VAYELEH) return getTorahSectionLinkHelper($DEUTERONOMY, 31, 1);

  if ($section == $ID_HAAZINU) return getTorahSectionLinkHelper($DEUTERONOMY, 32, 1);
  if ($section == $ID_SHEKALIM) return getTorahSectionLinkHelper($EXODUS, 30, 11);
  if ($section == $ID_ZAHOR) return getTorahSectionLinkHelper($DEUTERONOMY, 25, 17);
  if ($section == $ID_PARAH) return getTorahSectionLinkHelper($NUMERI, 19, 1);
  if ($section == $ID_HAHODESH) return getTorahSectionLinkHelper($EXODUS, 12, 1);
  return "";
}

function getLinkForShabbatHolidayReading($month, $day, $year) {
  if (cal_days_in_month(CAL_JEWISH, 3, $year) == 29)
    $shortKislev = true;
  else
    $shortKislev = false;

  if (torahHebrewLeapYear($year))
    $lastMonth = 13;
  else
    $lastMonth = 12;

  $result = "";

  $GENESIS = 1;
  $EXODUS = 2;
  $LEVITICUS = 3;
  $NUMBERS = 4;
  $DEUTERONOMY = 5;

  //------- Tishri
  if ($day == 1 && $month == 1) { // 1st day of Rosh Hashanah
    $result = array(getTorahSectionLinkHelper($GENESIS, 21, 1),
                    getTorahSectionLinkHelper($NUMBERS, 29, 1));
  }
  if ($day == 2 && $month == 1) { // 2nd day of Rosh Hashanah
    $result = array(getTorahSectionLinkHelper($GENESIS, 22, 1),
                    getTorahSectionLinkHelper($NUMBERS, 29, 1));
  }
  if ($day == 10 && $month == 1) { // Yom Kippur
    $result = array(getTorahSectionLinkHelper($LEVITICUS, 16, 1),
                    getTorahSectionLinkHelper($NUMBERS, 29, 7),
                    getTorahSectionLinkHelper($LEVITICUS, 18, 1));
  }
  if ($day == 15 && $month == 1) { // Sukkot I
    $result = array(getTorahSectionLinkHelper($LEVITICUS, 22, 26),
                    getTorahSectionLinkHelper($NUMBERS, 29, 12));
  }
  if ($day == 16 && $month == 1) { // Sukkot II
    $result = array(getTorahSectionLinkHelper($LEVITICUS, 22, 26),
                    getTorahSectionLinkHelper($NUMBERS, 29, 12));
  }
  if ($day == 17 && $month == 1) { // Sukkot III
    $result = array(getTorahSectionLinkHelper($EXODUS, 33, 12),
                    getTorahSectionLinkHelper($NUMBERS, 29, 17));
  }
  if ($day == 18 && $month == 1) { // Sukkot IV
    $result = array(getTorahSectionLinkHelper($NUMBERS, 29, 20));
  }
  if ($day == 19 && $month == 1) { // Sukkot V
    $result = array(getTorahSectionLinkHelper($EXODUS, 33, 12),
                    getTorahSectionLinkHelper($NUMBERS, 29, 23));
  }
  if ($day == 20 && $month == 1) { // Sukkot VI
    $result = array(getTorahSectionLinkHelper($EXODUS, 33, 12),
                    getTorahSectionLinkHelper($NUMBERS, 29, 23));
  }
  if ($day == 21 && $month == 1) { // Hoshanah Rabbah
    $result = array(getTorahSectionLinkHelper($NUMBERS, 29, 26));
  }
  if ($day == 22 && $month == 1) { // Shemini Azereth
    $result = array(getTorahSectionLinkHelper($DEUTERONOMY, 14, 22),
                    getTorahSectionLinkHelper($NUMBERS, 29, 35));
  }
  if ($day == 23 && $month == 1) { // Simchat Torah
    $result = array(getTorahSectionLinkHelper($DEUTERONOMY, 33, 1),
                    getTorahSectionLinkHelper($GENESIS, 1, 1),
                    getTorahSectionLinkHelper($NUMBERS, 29, 35));
  }

  //------- Kislev/Tevet
  if ($day == 25 && $month == 3) { // Chanukkah I
    $result = array(getTorahSectionLinkHelper($NUMBERS, 7, 1));
  }
  if ($day == 26 && $month == 3) { // Chanukkah II
    $result = array(getTorahSectionLinkHelper($NUMBERS, 7, 18));
  }
  if ($day == 27 && $month == 3) { // Chanukkah III
    $result = array(getTorahSectionLinkHelper($NUMBERS, 7, 24));
  }
  if ($day == 28 && $month == 3) { // Chanukkah IV
    $result = array(getTorahSectionLinkHelper($NUMBERS, 7, 30));
  }
  if ($day == 29 && $month == 3) { // Chanukkah V
    $result = array(getTorahSectionLinkHelper($NUMBERS, 7, 36));
  }
  if (($shortKislev && $day == 1 && $month == 4) ||
      (!$shortKislev && $day == 30 && $month == 3)) { // Chanukkah VI
    $result = array(getTorahSectionLinkHelper($NUMBERS, 7, 42));
  }
  if (($shortKislev && $day == 2 && $month == 4) ||
      (!$shortKislev && $day == 1 && $month == 4)) { // Chanukkah VII
    $result = array(getTorahSectionLinkHelper($NUMBERS, 7, 48));
  }
  if (($shortKislev && $day == 3 && $month == 4) ||
      (!$shortKislev && $day == 2 && $month == 4)) { // Chanukkah VIII
    $result = array(getTorahSectionLinkHelper($NUMBERS, 7, 54));
  }

  //------- Adar/Adar II
  if ($day == 14 && $month == $lastMonth) { // Purim
    $result = array(getTorahSectionLinkHelper($EXODUS, 17, 8));
  }

  //------- Nisan
  if ($day == 15 && $month == 8) { // Pesach I
    $result = array(getTorahSectionLinkHelper($EXODUS, 12, 21),
                    getTorahSectionLinkHelper($NUMBERS, 28, 16));
  }
  if ($day == 16 && $month == 8) { // Pesach II
    $result = array(getTorahSectionLinkHelper($LEVITICUS, 22, 26),
                    getTorahSectionLinkHelper($NUMBERS, 28, 16));
  }
  if ( (($day >= 17) && ($day <= 20)) && $month == 8) { // Hol Hamoed Pesah
    $result = array(getTorahSectionLinkHelper($EXODUS, 33, 12),
                    getTorahSectionLinkHelper($NUMBERS, 28, 19));
  }
  if ($day == 21 && $month == 8) { // Pesach VII
    $result = array(getTorahSectionLinkHelper($EXODUS, 13, 17),
                    getTorahSectionLinkHelper($NUMBERS, 28, 19));
  }
  if ($day == 22 && $month == 8) { // Pesach VIII
    $result = array(getTorahSectionLinkHelper($DEUTERONOMY, 14, 22),
                    getTorahSectionLinkHelper($NUMBERS, 28, 19));
  }

  //------- Sivan
  if ($day == 6 && $month == 10) { // Shavuot I
    $result = array(getTorahSectionLinkHelper($EXODUS, 19, 1),
                    getTorahSectionLinkHelper($NUMBERS, 28, 26));
  }
  if ($day == 7 && $month == 10) { // Shavuot II
    $result = array(getTorahSectionLinkHelper($EXODUS, 14, 22),
                    getTorahSectionLinkHelper($NUMBERS, 28, 26));
  }

  return $result;
}

function getLinkForShabbatRoshHodeshReading() {
  $GENESIS = 1;
  $EXODUS = 2;
  $LEVITICUS = 3;
  $NUMBERS = 4;
  $DEUTERONOMY = 5;

  return getTorahSectionLinkHelper($NUMBERS, 28, 9);
}

function getTorahSections($hebrewMonth, $hebrewDay, $hebrewYear) {
  global $ID_NULL, $ID_SHUVA;
  global $torahSectionsA, $torahSectionsB;
  global $torahSectionsCDiaspora, $torahSectionsCIsrael;
  global $torahSectionsDDiaspora, $torahSectionsDIsrael;
  global $torahSectionsEDiaspora, $torahSectionsEIsrael;
  global $torahSectionsF, $torahSectionsG;
  global $torahSectionsHDiaspora, $torahSectionsHIsrael;
  global $torahSectionsI, $torahSectionsJ;
  global $torahSectionsKDiaspora, $torahSectionsKIsrael;
  global $torahSectionsLDiaspora, $torahSectionsLIsrael;
  global $torahSectionsM;
  global $torahSectionsNDiaspora, $torahSectionsNIsrael;

  $shuvahDate = jewishtojd(1, 1, $hebrewYear)+1;
  while (torahGetWeekday($shuvahDate) != 6) {
    $shuvahDate++;
  }

  $torahDate = jewishtojd($hebrewMonth, $hebrewDay, $hebrewYear);
  if (torahGetWeekday($torahDate) == 6) {
    $bereshithDate = determineBereshith($hebrewYear);
    if ($torahDate < $bereshithDate)
      $referenceYear = $hebrewYear-1;
    else
      $referenceYear = $hebrewYear;

    $yearType = getYearType($referenceYear);
    $bereshithDate = determineBereshith($referenceYear);
    $torahWeekNo = ($torahDate-$bereshithDate)/7;

    $returnTorahSection = "";
    $idTorah1 = $ID_NULL;
    $idTorah2 = $ID_NULL;
    $idTorah3 = $ID_NULL;
/*
allgemein: A, B, F, G, I, J, M
Israel/Diaspora: C, D, E, H, K, L, N
*/

    switch ($yearType) {
      case 1: /* A */
        $idTorah1 = $torahSectionsA[$torahWeekNo * 3 + 0];
        $idTorah2 = $torahSectionsA[$torahWeekNo * 3 + 1];
        $idTorah3 = $torahSectionsA[$torahWeekNo * 3 + 2];
	break;
      case 2: /* B */
        $idTorah1 = $torahSectionsB[$torahWeekNo * 3 + 0];
        $idTorah2 = $torahSectionsB[$torahWeekNo * 3 + 1];
        $idTorah3 = $torahSectionsB[$torahWeekNo * 3 + 2];
	break;
      case 3: /* C */
	if (isDiaspora()) {
          $idTorah1 = $torahSectionsCDiaspora[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsCDiaspora[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsCDiaspora[$torahWeekNo * 3 + 2];
	} else {
          $idTorah1 = $torahSectionsCIsrael[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsCIsrael[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsCIsrael[$torahWeekNo * 3 + 2];
	}
	break;
      case 4: /* D */
	if (isDiaspora()) {
          $idTorah1 = $torahSectionsDDiaspora[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsDDiaspora[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsDDiaspora[$torahWeekNo * 3 + 2];
	} else {
          $idTorah1 = $torahSectionsDIsrael[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsDIsrael[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsDIsrael[$torahWeekNo * 3 + 2];
	}
	break;
      case 5: /* E */
	if (isDiaspora()) {
          $idTorah1 = $torahSectionsEDiaspora[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsEDiaspora[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsEDiaspora[$torahWeekNo * 3 + 2];
	} else {
          $idTorah1 = $torahSectionsEIsrael[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsEIsrael[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsEIsrael[$torahWeekNo * 3 + 2];
	}
	break;
      case 6: /* F */
        $idTorah1 = $torahSectionsF[$torahWeekNo * 3 + 0];
        $idTorah2 = $torahSectionsF[$torahWeekNo * 3 + 1];
        $idTorah3 = $torahSectionsF[$torahWeekNo * 3 + 2];
	break;
      case 7: /* G */
        $idTorah1 = $torahSectionsG[$torahWeekNo * 3 + 0];
        $idTorah2 = $torahSectionsG[$torahWeekNo * 3 + 1];
        $idTorah3 = $torahSectionsG[$torahWeekNo * 3 + 2];
	break;
      case 8: /* H */
	if (isDiaspora()) {
          $idTorah1 = $torahSectionsHDiaspora[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsHDiaspora[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsHDiaspora[$torahWeekNo * 3 + 2];
	} else {
          $idTorah1 = $torahSectionsHIsrael[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsHIsrael[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsHIsrael[$torahWeekNo * 3 + 2];
	}
	break;
      case 9: /* I */
        $idTorah1 = $torahSectionsI[$torahWeekNo * 3 + 0];
        $idTorah2 = $torahSectionsI[$torahWeekNo * 3 + 1];
        $idTorah3 = $torahSectionsI[$torahWeekNo * 3 + 2];
	break;
      case 10: /* J */
        $idTorah1 = $torahSectionsJ[$torahWeekNo * 3 + 0];
        $idTorah2 = $torahSectionsJ[$torahWeekNo * 3 + 1];
        $idTorah3 = $torahSectionsJ[$torahWeekNo * 3 + 2];
	break;
      case 11: /* K */
	if (isDiaspora()) {
          $idTorah1 = $torahSectionsKDiaspora[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsKDiaspora[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsKDiaspora[$torahWeekNo * 3 + 2];
	} else {
          $idTorah1 = $torahSectionsKIsrael[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsKIsrael[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsKIsrael[$torahWeekNo * 3 + 2];
	}
	break;
      case 12: /* L */
	if (isDiaspora()) {
          $idTorah1 = $torahSectionsLDiaspora[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsLDiaspora[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsLDiaspora[$torahWeekNo * 3 + 2];
	} else {
          $idTorah1 = $torahSectionsLIsrael[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsLIsrael[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsLIsrael[$torahWeekNo * 3 + 2];
	}
	break;
      case 13: /* M */
        $idTorah1 = $torahSectionsM[$torahWeekNo * 3 + 0];
        $idTorah2 = $torahSectionsM[$torahWeekNo * 3 + 1];
        $idTorah3 = $torahSectionsM[$torahWeekNo * 3 + 2];
	break;
      case 14: /* N */
	if (isDiaspora()) {
          $idTorah1 = $torahSectionsNDiaspora[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsNDiaspora[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsNDiaspora[$torahWeekNo * 3 + 2];
	} else {
          $idTorah1 = $torahSectionsNIsrael[$torahWeekNo * 3 + 0];
          $idTorah2 = $torahSectionsNIsrael[$torahWeekNo * 3 + 1];
          $idTorah3 = $torahSectionsNIsrael[$torahWeekNo * 3 + 2];
	}
	break;
    }

    if ($idTorah1 != $ID_NULL) {
      $torahSection = getTorahSectionName($idTorah1);
      $link = getTorahSectionLink($idTorah1);
      if ($torahSection != "") {
	if ($returnTorahSection != "")
	  $returnTorahSection = $returnTorahSection . ", ";
	$returnTorahSection = $returnTorahSection . $torahSection;
        if ($link != "") {
          $returnTorahSection = $returnTorahSection . " " . makeLink($link);
        }
      }
    }
    if ($idTorah2 != $ID_NULL) {
      $torahSection = getTorahSectionName($idTorah2);
      $link = getTorahSectionLink($idTorah2);
      if ($torahSection != "") {
	if ($returnTorahSection != "")
	  $returnTorahSection = $returnTorahSection . ", ";
	$returnTorahSection = $returnTorahSection . $torahSection;
        if ($link != "") {
          $returnTorahSection = $returnTorahSection . " " . makeLink($link);
        }
      }
    }
    if ($idTorah3 != $ID_NULL) {
      $torahSection = getTorahSectionName($idTorah3);
      $link = getTorahSectionLink($idTorah3);
      if ($torahSection != "") {
	if ($returnTorahSection != "")
	  $returnTorahSection = $returnTorahSection . ", ";
	$returnTorahSection = $returnTorahSection . $torahSection;
        if ($link != "") {
          $returnTorahSection = $returnTorahSection . " " . makeLink($link);
        }
      }
    }
    if ($torahDate == $shuvahDate) {
      if ($returnTorahSection != "")
	$returnTorahSection = $returnTorahSection . ", ";
      $returnTorahSection = $returnTorahSection . getTorahSectionName($ID_SHUVA);
    }

    return ($returnTorahSection);
  } else {
    return "";
  }
}
?>
